infra:
    log_dir: ./ # where all the experiments are
    exp_name: fastglioma/ # use the same name as the training experiment
    comment: scm_vicreg_dev # can use this to customize for each experiment
    seed: 1000
data:
    db_root: /path/to/opensrh/
    embedding_root: /path/to/embeddings/
    train_augmentation: []
    valid_augmentation: same
    rand_aug_prob: 1.
    tag: [tag1] # specify tag for eval
model:
    backbone: 
        which: transformer
        params:
            embed_dim: 512
            depth: 2
            num_heads: 4
            pos_emb_type: FFPEG
            pos_emb_grad: True
            prefix_len: 8
    mlp_hidden: [512]
    num_embedding_out: 128
    train_alg: scm
eval:
    predict_batch_size: 128
    knn:
        batch_size: 128
        k: 10
        t: 0.07
    ckpt_path: relative/path/to/checkpoint.ckpt # eg. hash_datetime_expname_comment/models/ckpt-epochXX-accXXX.ckpt
