infra:
    log_dir: ./ # where all the experiments are
    exp_name: fastglioma/ # where you want to save the inference results
    comment: save_embed # can use this to customize for each save
    seed: 1000
data:
    db_root: /path/to/opensrh/
    studies: val # train/val or specify studies (e.g., ["NIO_001", "NIO_004"])
    train_augmentation: []
    valid_augmentation:
        - which: inpaint_rows_always_apply
          params: 
            image_size: 300
            y_skip: 5
    srh_base_augmentation: three_channels
    rand_aug_prob: 0.3
model:
    backbone:
        which: resnet34
        params:
            num_channel_in: 3 # {1: lowres, 3: highres}
    mlp_hidden: []
    num_embedding_out: 128
eval:
    predict_batch_size: 128
    ckpt_path: /path/to/pretrained/ckpt
    save_by_slide:
        saving_dir: /path/to/embeddings/
        tag: tag1