infra:
    log_dir: ./ # where all the experiments are
    exp_name: fastglioma/ # where you want to save the inference results
    comment: inference # can use this to customize for each inference
    hf_repo: mlinslab/fastglioma # specify huggingface repo to be used
    seed: 1000
data:
    db_root: /path/to/opensrh/
    studies: ["NIO_001"] # val or specify studies (e.g., ["NIO_001", "NIO_004"])
    patch_input: highres # {highres, lowres}
    use_patient_class: true # whether to use patient or slide class for inference
model:
    patch:
        backbone:
            which: resnet34
            params:
                num_channel_in: 3 # {1: lowres, 3: highres}
        mlp_hidden: []
        num_embedding_out: 128
    slide:
        mil:
            which: transformer
            params:
                embed_dim: 512
                depth: 2
                num_heads: 4
                pos_emb_type: FFPEG
                pos_emb_grad: True
                prefix_len: 8
        mlp_hidden: [512]
eval:
    predict_batch_size: 4 # keep low to avoid opening too many image files at once
    ckpt_path: fastglioma_highres_model.ckpt # path to ckpt in huggingface repo